apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  namespace: kube-system
  name: csi-baremetal-scheduler
spec:
  selector:
    matchLabels:
      app: csi-baremetal-scheduler
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-baremetal-scheduler
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: csi-baremetal-scheduler-sa
      containers:
        - name: scheduler
          args:
            - --address=0.0.0.0
            - --leader-elect=false
            - --scheduler-name=csi-baremetal-scheduler
          image: {{- if .Values.env.test }} csi-baremetal-scheduler:{{ .Values.image.tag }}
            {{- else }} {{ .Values.registry }}/csi-baremetal-scheduler:{{ .Values.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10251
          resources:
            requests:
              cpu: '0.1'
          securityContext:
            privileged: false
          volumeMounts: []
      hostNetwork: false
      hostPID: false
      volumes: []
