output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

linters-settings:
  lll:
    line-length: 190
  funlen:
    lines: 180
    statements: 70
  gocognit:
    min-complexity: 60
  golint:
    # godoc says that one of files from a package should contain package comment.
    # but golint has constraint that checks package comment in every file of the package.
    # golint developers mention that this is imperfection. https://github.com/golang/lint/blob/master/lint.go#L376
    # To prevent this checking set min-confidence level to 0.3
    min-confidence: 0.3

linters:
  # please, do not use `enable-all`: it is deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    # - contextcheck TODO - https://github.com/dell/csi-baremetal/issues/703
    # - cyclop TODO - https://github.com/dell/csi-baremetal/issues/832
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    # - errname
    # - errorlint
    - exhaustive
    # - exhaustivestruct
    - exportloopref
    - forbidigo
    # - forcetypeassert
    - funlen
    # - gci
    # - gochecknoglobals - TODO https://github.com/dell/csi-baremetal/issues/474
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godot No need
    # - godox CSI now has a lot TODOs in source code
    # - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    # - gomnd - TODO https://github.com/dell/csi-baremetal/issues/836
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    # - gosec Because CSI uses lsblk servers for now
    - gosimple
    - govet
    # - ifshort
    - importas
    - ineffassign
    # - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    # - nestif - TODO https://github.com/dell/csi-baremetal/issues/837
    # - nilerr
    # - nilnil
    # - nlreturn
    # - noctx
    - nolintlint
    - paralleltest
    - prealloc
    # - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    # - stylecheck
    # - tagliatelle - TODO https://github.com/dell/csi-baremetal/issues/834
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    # - varnamelen No need
    - wastedassign
    - whitespace
    # - wrapcheck - TODO https://github.com/dell/csi-baremetal/issues/833
    # - wsl

run:
  deadline: 15m
  timeout:  15m

  skip-dirs:
    - test/
    - vendor/
    - api/
  skip-files:
    - .*_test.go
    - .*.pb.go

# golint is disabled by default in golang-ci because of golang community
issues:
  exclude-use-default: false
