include variables.mk

### Lint

lint:
	${GO_ENV_VARS} golangci-lint -v run ./...

lint-charts:
	helm lint ./${DRIVER_CHART_PATH}
	helm lint ./${EXTENDER_CHART_PATH}
	helm lint ./${OPERATOR_CHART_PATH}
	helm lint ./${SCHEDULER_CHART_PATH}

### Unit tests

coverage:
	go tool cover -html=coverage.out -o coverage.html

test:
	${GO_ENV_VARS} go test `go list ./... | grep -v halmgr` -race -cover -coverprofile=coverage.out

# Run tests for pr-validation with writing output to log file
# Test are different (ginkgo, go testing, etc.) so can't use native ginkgo methods to print junit output.
test-pr-validation:
	${GO_ENV_VARS} go test `go list ./... | grep -v halmgr` -v -race -cover -coverprofile=coverage.out > log.txt

install-junit-report:
	${GO_ENV_VARS} go get -u github.com/jstemmer/go-junit-report

# Convert go test output from log.txt to junit-style output. Split these steps because no matter if test fails,
# junit output must be collected
pr-validation-junit:
	cat log.txt >&1 | go-junit-report > report.xml

### E2E

# Run e2e tests for CI. All of these tests use ginkgo so we can use native ginkgo methods to print junit output.
# Also go test doesn't provide functionnality to save test's log into the file. Use > to archieve artifatcs.
test-ci:
	${GO_ENV_VARS} CI=true go test -v test/e2e/baremetal_e2e_test.go -ginkgo.v -ginkgo.progress -kubeconfig=${HOME}/.kube/config -timeout=0 > log.txt

test-ci-with-operator:
	${GO_ENV_VARS} CI=true CSI_VERSION=${CSI_VERSION} OPERATOR_VERSION=${OPERATOR_VERSION} go test -v test/e2e_operator/baremetal_e2e_test.go -ginkgo.v -ginkgo.progress -kubeconfig=${HOME}/.kube/config -timeout=0 > log.txt

# Run commnity sanity tests for CSI. TODO https://github.com/dell/csi-baremetal/issues/298 Make sanity test work for expansion
# TODO enable tests back - https://github.com/dell/csi-baremetal/issues/371
test-sanity:
#	${GO_ENV_VARS} SANITY=true go test test/sanity/sanity_test.go -ginkgo.skip \
#	"ExpandVolume|\
#	ValidateVolumeCapabilities|\
#	should fail when the node does not exist|\
#	should fail when requesting to create a volume with already existing name and different capacity|\
#	should not fail when requesting to create a volume with already existing name and same capacity" -ginkgo.v -timeout=0

load-helm-charts:
	wget -P ./charts https://asdrepo.isus.emc.com/artifactory/atlantic-helm-build/csi-operator/${OPERATOR_VERSION}/csi-baremetal-operator-${OPERATOR_VERSION}.tgz
	wget -P ./charts https://asdrepo.isus.emc.com/artifactory/atlantic-helm-build/csi-operator/${OPERATOR_VERSION}/csi-baremetal-deployment-${OPERATOR_VERSION}.tgz
	tar -xzvf ./charts/csi-baremetal-operator-${OPERATOR_VERSION}.tgz
	tar -xzvf ./charts/csi-baremetal-deployment-${OPERATOR_VERSION}.tgz

load-Operator-image:
	docker pull ${registry}/csi-baremetal-operator:${operatorVersion}
	docker tag ${registry}/csi-baremetal-operator:${operatorVersion} csi-baremetal-operator:${operatorVersion}
	kind load docker-image csi-baremetal-operator:${operatorVersion}

kind-pull-images: kind-pull-sidecar-images
	docker pull ${REGISTRY}/${PROJECT}-${LOOPBACK_DRIVE_MGR}:${TAG}
	docker pull ${REGISTRY}/${PROJECT}-${NODE}:${TAG}
	docker pull ${REGISTRY}/${PROJECT}-${NODE}-kernel-5.4:${TAG}
	docker pull ${REGISTRY}/${PROJECT}-${CONTROLLER}:${TAG}
	docker pull ${REGISTRY}/${PROJECT}-${SCHEDULER}-${EXTENDER}:${TAG}
	docker pull ${REGISTRY}/${PROJECT}-${EXTENDER_PATCHER}:${TAG}
	docker pull ${REGISTRY}/${PROJECT}-${SCHEDULER}:${TAG}
	docker pull ${REGISTRY}/${PROJECT}-${OPERATOR}:${TAG}

kind-pull-sidecar-images:
	docker pull ${REGISTRY}/${CSI_PROVISIONER}:${CSI_PROVISIONER_TAG}
	docker pull ${REGISTRY}/${CSI_REGISTRAR}:${CSI_REGISTRAR_TAG}
	docker pull ${REGISTRY}/${CSI_ATTACHER}:${CSI_ATTACHER_TAG}
	docker pull ${REGISTRY}/${LIVENESS_PROBE}:${LIVENESS_PROBE_TAG}
	docker pull ${REGISTRY}/${CSI_RESIZER}:${CSI_RESIZER_TAG}
	docker pull ${REGISTRY}/${BUSYBOX}:${BUSYBOX_TAG}
	docker pull ${REGISTRY}/library/nginx:1.14-alpine

kind-tag-images:
	docker tag ${REGISTRY}/${CSI_PROVISIONER}:${CSI_PROVISIONER_TAG} ${CSI_PROVISIONER}:${CSI_PROVISIONER_TAG}
	docker tag ${REGISTRY}/${CSI_REGISTRAR}:${CSI_REGISTRAR_TAG} ${CSI_REGISTRAR}:${CSI_REGISTRAR_TAG}
	docker tag ${REGISTRY}/${CSI_ATTACHER}:${CSI_ATTACHER_TAG} ${CSI_ATTACHER}:${CSI_ATTACHER_TAG}
	docker tag ${REGISTRY}/${CSI_RESIZER}:${CSI_RESIZER_TAG} ${CSI_RESIZER}:${CSI_RESIZER_TAG}
	docker tag ${REGISTRY}/${LIVENESS_PROBE}:${LIVENESS_PROBE_TAG} ${LIVENESS_PROBE}:${LIVENESS_PROBE_TAG}
	docker tag ${REGISTRY}/${BUSYBOX}:${BUSYBOX_TAG} ${BUSYBOX}:${BUSYBOX_TAG}
	docker tag ${REGISTRY}/library/nginx:1.14-alpine docker.io/library/nginx:1.14-alpine
	docker tag ${REGISTRY}/${PROJECT}-${LOOPBACK_DRIVE_MGR}:${TAG} ${PROJECT}-${LOOPBACK_DRIVE_MGR}:${TAG}
	docker tag ${REGISTRY}/${PROJECT}-${NODE}:${TAG} ${PROJECT}-${NODE}:${TAG}
	docker tag ${REGISTRY}/${PROJECT}-${NODE}-kernel-5.4:${TAG} ${PROJECT}-${NODE}-kernel-5.4:${TAG}
	docker tag ${REGISTRY}/${PROJECT}-${CONTROLLER}:${TAG} ${PROJECT}-${CONTROLLER}:${TAG}
	docker tag ${REGISTRY}/${PROJECT}-${SCHEDULER}-${EXTENDER}:${TAG} ${PROJECT}-${SCHEDULER}-${EXTENDER}:${TAG}
	docker tag ${REGISTRY}/${PROJECT}-${EXTENDER_PATCHER}:${TAG} ${PROJECT}-${EXTENDER_PATCHER}:${TAG}
	docker tag ${REGISTRY}/${PROJECT}-${SCHEDULER}:${TAG} ${PROJECT}-${SCHEDULER}:${TAG}
	docker tag ${REGISTRY}/${PROJECT}-${OPERATOR}:${TAG} ${PROJECT}-${OPERATOR}:${TAG}

kind-load-images:
	kind load docker-image ${CSI_PROVISIONER}:${CSI_PROVISIONER_TAG}
	kind load docker-image ${CSI_REGISTRAR}:${CSI_REGISTRAR_TAG}
	kind load docker-image ${CSI_ATTACHER}:${CSI_ATTACHER_TAG}
	kind load docker-image ${CSI_RESIZER}:${CSI_RESIZER_TAG}
	kind load docker-image ${LIVENESS_PROBE}:${LIVENESS_PROBE_TAG}
	kind load docker-image ${BUSYBOX}:${BUSYBOX_TAG}
	kind load docker-image docker.io/library/nginx:1.14-alpine
	kind load docker-image ${PROJECT}-${LOOPBACK_DRIVE_MGR}:${TAG}
	kind load docker-image ${PROJECT}-${NODE}:${TAG}
	kind load docker-image ${PROJECT}-${NODE}-kernel-5.4:${TAG}
	kind load docker-image ${PROJECT}-${CONTROLLER}:${TAG}
	kind load docker-image ${PROJECT}-${SCHEDULER}-${EXTENDER}:${TAG}
	kind load docker-image ${PROJECT}-${EXTENDER_PATCHER}:${TAG}
	kind load docker-image ${PROJECT}-${SCHEDULER}:${TAG}
	kind load docker-image ${PROJECT}-${OPERATOR}:${TAG}
