apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-baremetal-se-config
  namespace: kube-system
data:
  policy.yaml : |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: default-scheduler
    algorithmSource:
      policy:
        file:
          path: {{ .Values.scheduler.policy.path }}
    leaderElection:
      leaderElect: true
    clientConnection:
      kubeconfig: {{ .Values.scheduler.conf.path }}
