FROM    ubuntu:21.04

ADD     health_probe    health_probe

# On Ubuntu 21.04 fdisk is not installed by defaul
RUN     apt update --no-install-recommends -y -q; apt install --no-install-recommends -y -q util-linux parted xfsprogs lvm2 fdisk gdisk strace udev net-tools
