apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-operator-sa
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-operator-cr
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["csi-baremetal.dell.com"]
    resources: ["nodes"]
    verbs: ["watch", "get", "list", "create", "delete", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-operator-rb
subjects:
  - kind: ServiceAccount
    name: csi-operator-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-operator-cr
  apiGroup: rbac.authorization.k8s.io
