loader.loadFrom('pipelines': [common : 'common',])

PROVISION_VERSION = 'v1.2.2'
ATTACHER_VERSION = 'v1.0.1'
NODE_REGISTRAR_VERSION = 'v1.0.1-gke.0'

COMPONENT_NAME = 'csi'
ARTIFACTORY_NAME = common.ARTIFACTORY.ATLANTIC_BUILD_REPO_NAME
ARTIFACTORY_REPO = common.ARTIFACTORY.getUrlForRepo(ARTIFACTORY_NAME)
ARTIFACTORY_ATLANTIC_DIR_PATH = 'com/emc/atlantic'
ARTIFACTORY_ATLANTIC_CHARTS_DIR_PATH = "${ARTIFACTORY_ATLANTIC_DIR_PATH}/charts"
ARTIFACTORY_COMPONENT_PATH = "${ARTIFACTORY_REPO}/${ARTIFACTORY_ATLANTIC_DIR_PATH}/${COMPONENT_NAME}"
ARTIFACTORY_CHARTS_PATH = "/artifactory/${ARTIFACTORY_NAME}/${ARTIFACTORY_ATLANTIC_CHARTS_DIR_PATH}/${COMPONENT_NAME}"
ARTIFACTORY_FULL_CHARTS_PATH = "${ARTIFACTORY_REPO}/${ARTIFACTORY_ATLANTIC_CHARTS_DIR_PATH}/${COMPONENT_NAME}"
ARTIFACTORY_FILE_PATH = "/artifactory/${ARTIFACTORY_NAME}/${ARTIFACTORY_ATLANTIC_DIR_PATH}/${COMPONENT_NAME}"
