FROM    ubuntu:18.04

ADD     health_probe    health_probe

#RUN     apk add bash curl util-linux parted xfsprogs-extra lvm2 sgdisk
RUN     apt update --no-install-recommends -y -q; apt install --no-install-recommends -y -q bash curl util-linux
