apiVersion: v1
kind: Policy
extenders:
  - urlPrefix: "http://127.0.0.1:8889"
    filterVerb: filter
    #prioritizeVerb: prioritize
    #bindVerb: bind
    enableHttps: false
    nodeCacheCapable: false
    ignorable: true
#    tlsConfig:
#      certFile:
#      keyFile:
