{{- if .Values.patcher.enable }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: csi-baremetal-se-patcher
spec:
  selector:
    matchLabels:
      app: csi-baremetal-se-patcher
  template:
    metadata:
      labels:
        app: csi-baremetal-se-patcher
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: schedulerpatcher
          image: {{- if .Values.env.test }} csi-baremetal-scheduler-patcher:{{ .Values.image.tag }}
            {{- else }} {{ .Values.registry }}/csi-baremetal-scheduler-patcher:{{ .Values.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python3
            - -u
            - main.py
          args:
            - --loglevel={{ .Values.log.level }}
            {{ if .Values.patcher.restore_on_shutdown }}- --restore {{ end }}
            - --interval={{ .Values.patcher.interval }}
            - --platform={{ .Values.patcher.platform }}
            - --source-config-path=/config/{{ .Values.patcher.source_config_path}}
            - --source-policy-path=/config/{{ .Values.patcher.source_policy_path}}
            - --source_config_19_path=/config/{{ .Values.patcher.source_config_19_path}}
            {{- if eq .Values.patcher.platform "rke" }}
            - --target-config-path={{ .Values.patcher.rke.target_config_path}}
            - --target-policy-path={{ .Values.patcher.rke.target_policy_path}}
            - --target_config_19_path={{ .Values.patcher.rke.target_config_19_path}}
            - --backup-path={{ .Values.patcher.rke.kube_scheduler}}
            {{- else }}
            - --target-config-path={{ .Values.patcher.target_config_path}}
            - --target-policy-path={{ .Values.patcher.target_policy_path}}
            - --target_config_19_path={{ .Values.patcher.target_config_19_path}}
            - --backup-path={{ .Values.patcher.kube_scheduler}}
            {{- end}}
          volumeMounts:
            - mountPath: /crash-dump
              name: crash-dump
            - mountPath: /config
              name: schedulerpatcher-config
              readOnly: true
            {{- if eq .Values.patcher.platform "rke" }}
            - mountPath: {{ .Values.patcher.rke.kube_manifests }}
              name: kubernetes-manifests
            - mountPath: {{ .Values.patcher.rke.kube_scheduler }}
              name: kubernetes-scheduler
            {{- else }}
            - mountPath: {{ .Values.patcher.kube_manifests }}
              name: kubernetes-manifests
            - mountPath: {{ .Values.patcher.kube_scheduler }}
              name: kubernetes-scheduler
            {{- end}}
      volumes:
        - name: crash-dump
          emptyDir: {}
        {{- if .Values.patcher.enable }}
        - name: schedulerpatcher-config
          configMap:
            name: {{ .Values.patcher.config_map_name }}
        {{- if eq .Values.patcher.platform "rke" }}
        - name: kubernetes-manifests
          hostPath:
            path: {{ .Values.patcher.rke.kube_manifests }}
        - name: kubernetes-scheduler
          hostPath:
            path: {{ .Values.patcher.rke.kube_scheduler }}
        {{- else }}
        - name: kubernetes-manifests
          hostPath:
            path: {{ .Values.patcher.kube_manifests }}
        - name: kubernetes-scheduler
          hostPath:
            path: {{ .Values.patcher.kube_scheduler }}
        {{- end }}
      {{- end }}
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
{{- end }}
