name: pull request comment
on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
      - name: say hello
        if: contains(github.event.comment.body, '/support')
        run: |
          echo say hello
