name: Generated files consistency check

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build && test
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Prepare Golang 
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.3'
  
    - name: Compile proto files
      run: make install-compile-proto

    - name: Generate CRD
      run: |
        make install-controller-gen
        make generate-deepcopy
    - name: Change file in directory
      run: |
          echo "var Changed string" >> api/generated/v1/drivemgrsvc.pb.go
    
    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v5.5
      id: changed_files
      with:
        files: './api($|/.*.go)'
    - name: Display changed files
      if: steps.changed_files.outputs.files_changed == 'true'
      run: exit 1
       
    - name: Perform action when files change.
      if: steps.changed_files.outputs.files_changed == 'true'
      run: |
        echo "Do something when files have changed."
